Vectors

In [2]:
import numpy as np

u = np.array([5, 12])
print(u)

[ 5 12]


In [3]:
v = np.array([3, 4])
magnitude_v = np.linalg.norm(v)
print(magnitude_v)

5.0


In [4]:
# Dot product and orthogonal projection

a = np.array([1, 2])
b = np.array([3, 4])

dot_product = np.dot(a, b)

print("Dot product of a and b:", dot_product)

if dot_product == 0:
    print("a and b are orthogonal")
else:
    print("a and b are not orthogonal")

Dot product of a and b: 11
a and b are not orthogonal


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

C = A + B
print("Sum of A and B:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Sum of A and B:
 [[ 6  8]
 [10 12]]


In [ ]:
# Matrix multiplication
D = A @ B # or np.dot(A, B)
print("Product of A and B:\n", D)

Product of A and B:
 [[19 22]
 [43 50]]


In [7]:
# Transpose of a matrix
A_transpose = A.T
print("Transpose of A:\n", A_transpose)

Transpose of A:
 [[1 3]
 [2 4]]


In [8]:
# Identity and Inverse
I = np.eye(2)  # Identity matrix of size 2x2
print("Identity matrix I:\n", I)

A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Check A * A_inv = I
print("A * A_inv:\n", A @ A_inv)

Identity matrix I:
 [[1. 0.]
 [0. 1.]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A * A_inv:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

Determinant of A: -2.0000000000000004
Rank of A: 2
